// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_fTKbILoGmF3-3EFArihylQOPlAlqgEs',
    appId: '1:108928876199:web:5e6c18faf891a288886582',
    messagingSenderId: '108928876199',
    projectId: 'throw-43674',
    authDomain: 'throw-43674.firebaseapp.com',
    storageBucket: 'throw-43674.firebasestorage.app',
    measurementId: 'G-TRD80WFFR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyFmky3dngA9ZoQjq6JzeAJoG2CR8qS4M',
    appId: '1:108928876199:android:abcd7751174b56b1886582',
    messagingSenderId: '108928876199',
    projectId: 'throw-43674',
    storageBucket: 'throw-43674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjf70XAsrUbEkafeKq4l1sk8bJZwgMJF4',
    appId: '1:108928876199:ios:23068e310a989208886582',
    messagingSenderId: '108928876199',
    projectId: 'throw-43674',
    storageBucket: 'throw-43674.firebasestorage.app',
    iosClientId: '108928876199-oi5o4hmum4g86f99p76mrhsfiuhims1q.apps.googleusercontent.com',
    iosBundleId: 'com.throwapp.userapp',
  );
}
